# Generated by Django 2.1.7 on 2019-04-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='电影名称')),
                ('score', models.CharField(max_length=100, verbose_name='电影评分')),
            ],
            options={
                'verbose_name_plural': '电影',
            },
        ),
    ]
